### PR TITLE
Updated slides based on review

### PR DESCRIPTION
**Pull request by davidz627**

### CODE REVIEW

**Comment by jsafrane** [comment]
Actually, I'd like to have StorageClass overview (just a few sentences) there, because later you'll refer to it when describing `pvc.spec.storsageClassName`. IMO it would be confusing to refer to an object that has not been introduced.

**Comment by davidz627** [comment]
@jsafrane in that case I moved that slide after the "portability" slide, I think it flows a little better like that

**Comment by jsafrane** [comment]
Hmm, portability already mentions storage class, but if you feel better about it...

**Pull request merged**
